build:
  image: default-bionic
  nodes:
    analysis:
      dependencies:
        override:
          - composer install --ignore-platform-reqs --no-interaction
        before:
          - composer require --ignore-platform-reqs --no-interaction --dev johnpbloch/wordpress

filter:
  excluded_paths:
    - 'tests/*'
    - "*/ace-min-noconflict/*"
    - 'vendor/*'
    - '*/*.min.js'
    - 'js/fullcalendar/*'
    - 'js/jquery-validate/*'
    - 'js/dev/*'
    - 'js/min/*'
    - 'js/locale/*'
    - 'js/localization/*'
    - 'js/select2/*'
    - 'js/slick/*'
    - 'js/autofill-event.js'
    - 'js/leaflet.js'
    - 'js/responsive-tabs.js'
    - 'js/sorttable.js'
    - 'js/feedback.js'
    - 'js/dt.rowgroup.print.js'
  dependency_paths:
    - wordpress/
    - vendor/
    - titan-framework/
    - 'utils/phpqrcode.php'
    - 'utils/srdb.class.php'